# -*- coding: utf-8 -*-
"""copy-of-copy-of-mad_lib_project_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/coreED-Github/e5977942cdee5c2c9576edf0a56505aa/copy-of-copy-of-mad_lib_project_01.ipynb

**1. Project Introduction**

I created a Mad Libs Adventure Game where users answer specific questions, and based on their responses, a magical adventure story is generated.

**2. Welcome Message**

The game starts by greeting the user and explaining that they need to answer questions to create their adventure story.

**3. User Inputs**

The game asks users to provide:

An adjective to describe a place

An animal name

A mysterious object (noun)

A verb in the past tense

A place (real or magical)

The sound the animal makes

An emotion that everyone feels

**4. User Confirmation**

Once all inputs are collected, the user is asked to press Enter to proceed to the story creation.

**5. Generating the Story**

The game then creates a unique story by inserting the user’s inputs into a predefined story template, making it fun and personalized.

**6. Displaying the Story**

Finally, the game displays the complete story, incorporating all the words the user provided.
"""

# Mad_Libs Adventure Game
print("Welcome to the Magical Story Creator!")
print("Answer the following questions to build your adventure story...\n")

adjective1 = input("1. Enter an adjective (to describe a place): ")
animal = input("2. Name an animal: ")
noun1 = input("3. Enter a mysterious object (noun): ")
verb_past = input("4. Enter a verb (past tense): ")
place = input("5. Enter a magical or real place: ")
sound = input("6. What sound does the animal make? ")
emotion = input("7. How did everyone feel? (e.g., happy, scared, surprised): ")

input("\nAll set! Press Enter to 'Create Story'...")
print("\nHere's your magical story:\n")

story = f"""
In a {adjective1} forest far beyond the mountains, a curious {animal} roamed freely.
 {animal.capitalize()} was known for its love of exploring the unknown.
One bright morning, it stumbled upon a shiny {noun1} hidden beneath a pile of golden leaves.
Without a second thought, it {verb_past} and let out a loud '{sound.upper()}!' {sound.upper()}!!! {animal.capitalize()}’s voice echoed through the {adjective1} trees.
Everyone in the land of {place} heard the noise and rushed to see what had happened. People were {emotion}, eyes wide open and hearts pounding.
From that day on, the tale of the {animal} and the magical {noun1} spread like wildfire. It was the beginning of an epic adventure filled with laughter, wonder, and a bit of mystery.
And if you ever visit {place}, you might just hear that same sound again... '{sound}!' echoing through the trees.
The end.

{animal.capitalize()} says goodbye with a wave! {sound.upper()}!
"""
print(story)